### ISSUE TITLE
Support Anchors

### ISSUE THREAD

**Issue by dlasky** [dlasky/gotk3-layershell#1]
@nwg-piotr this was missing anchor support. added in the latest commits.

**Comment by nwg-piotr** [comment]
I'll give it a try this weekend. Real usage must wait till the current job is finished, sorry.

**Comment by dlasky** [comment]
no rush at all, i just wanted to let you know that i had missed something that big lol.

i guess the aur version of gtk-layer-shell is still at .5.4 too and the header i was looking at was for .6 so some of the stuff i was going to add may not matter yet.

**Comment by nwg-piotr** [comment]
I checked through the panel code, and these you are the functions I needed:

- init_for_window
- set_monitor
- auto_exclusive_zone_enable
- set_layer
- set_margin
- set_anchor

**Comment by dlasky** [comment]
I have all of those besides set monitor

**Comment by nwg-piotr** [comment]
Quite important on multi-headed setups. E.g. I use 4 panels on 3 outputs.

**Comment by dlasky** [comment]
Yeah I use 2 myself. I'll take a look at how gotk3 handles gtk.Monitor tomorrow prolly

**Comment by nwg-piotr** [comment]
No hurry. All the config GUI forms will take ages. :rofl:

**Comment by dlasky** [comment]
pushed monitor support. turns out i was using layer-shell-git package from the aur and it was severely out of date. switched to community which is like .5.2 or something and now its compiling.

**Comment by nwg-piotr** [comment]
Great job, can't wait to make use of it. But for now I'm still far from having the config GUI finished. Just the panel settings ready, working on modules.

![image](https://user-images.githubusercontent.com/20579136/107130018-0dd9eb80-68ca-11eb-98b1-b7a23e2fdf71.png)
