### ISSUE TITLE
gotk3 issue

### ISSUE THREAD

**Issue by nwg-piotr** [dlasky/gotk3-layershell#2]
Hi,

Sorry for bothering you with the problem not related to your code. I just hope you encountered it already and can suggest further steps.

When I try to build your `example.go`, I end up in such error:

```text
$ go get github.com/dlasky/gotk3-layershell/layershell
# github.com/gotk3/gotk3/gtk
../../go/pkg/mod/github.com/gotk3/gotk3@v0.5.2/gtk/accel.go:264:5: val.accel_flags undefined (type _Ctype_struct__GtkAccelKey has no field or method accel_flags)
../../go/pkg/mod/github.com/gotk3/gotk3@v0.5.2/gtk/accel.go:273:22: obj.accel_flags undefined (type *_Ctype_struct__GtkAccelKey has no field or method accel_flags)
```

I'm on `go version go1.16.2 linux/amd64` (Arch Linux). Downgrading go to 1.15 helps - everything works well. I'll submit the issue on the gotk3 repository, but I'd like to know your opinion first.

**Comment by dlasky** [comment]
I haven't built it on 1.16.2 yet been working on getting a sway environment on my pinephone hehe. I'll try in the morning and let you know.

There has also been a layer shell update since then.

**Comment by nwg-piotr** [comment]
Layer shell just warns about possible incompatibility, but works perfectly well - as well here, as in nwg-panel:

> ** (nwg-panel:47238): WARNING **: 01:31:07.136: gtk-layer-shell v0.6.0 may not work on GTK v3.24.27. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md

Thanks in advance for help.

**Comment by dlasky** [comment]
Same result, definitely looks like its upstream with gotk3

looks like its already been reported: https://github.com/gotk3/gotk3/issues/726

**Comment by nwg-piotr** [comment]
Thanks for confirming.

I remember trying to use `go get github.com/gotk3/gotk3@master` when the library didn't work with go1.15. It didn't work for me for some reason. Alright, I can downgrade go temporarily. What I'm going to use your library for is in the stage of early idea, with no deadline.

**Comment by dlasky** [comment]
no worries.

im workign on a small bar using it as well, but i may switch it to be pinephone specific, cause there are some unique considerations (rotation) for pinephone that might be kinda fun to tackle

**Comment by nwg-piotr** [comment]
I noticed. :)

Having optimized the `nwg-panel` code, I'm quite happy with its performance and resources usage, so I'll probably leave it on python forever. But to have all the shell components, I need a dock. Not that I'm going to use it, but it should look not bad. And I'd have an opportunity to learn some golang.
