### ISSUE TITLE
keybard input

### ISSUE THREAD

**Issue by nwg-piotr** [dlasky/gotk3-layershell#3]
Could we (please, please!) have also support for `gtk_layer_set_keyboard_mode`? I suppose this is the reason why the window does not respond to key events...

**Comment by dlasky** [comment]
lemme know if this does it for you: https://github.com/dlasky/gotk3-layershell/commit/ee90d3fa92c9a0d8593167fb3b83a06fe4f7f3a7

**Comment by dlasky** [comment]
also it looks like arch updated their package to 0.6.1 now so I can add a few more features as well that were not previously supported on 0.4.x

**Comment by nwg-piotr** [comment]
When set to `LAYER_SHELL_KEYBOARD_MODE_EXCLUSIVE`, it works. Doesn't seem to share the keyboard w/ other windows.

> looks like arch updated their package to 0.6.1

I'm still on 0.6.0 :/

**Comment by dlasky** [comment]
cool.  i dont know a ton about GTK but it could also be a window/input focus issue if you dont want to set exclusive.

**Comment by dlasky** [comment]
thanks for testing, i didn't add it to the example so i was hoping it worked lol

**Comment by nwg-piotr** [comment]
Thanks a lot for responding in minutes! Finally I'm not sure which way to use the keyboard in the dock, as what I actually want is just the Escape key. :D

**Comment by dlasky** [comment]
no worries, i was hacking on away-bar anyway and watching bad TV haha
