### ISSUE TITLE
gtk_layer_set_exclusive_zone

### ISSUE THREAD

**Issue by nwg-piotr** [dlasky/gotk3-layershell#4]
A Very Humble Request: could we also have [gtk_layer_set_exclusive_zone](https://github.com/wmww/gtk-layer-shell/blob/6ddf8f48a5659108550303dc84b99a472f9ef622/include/gtk-layer-shell.h#L307) implemented? :innocent: 

[edit] Sorry, nothing urgent, as it doesn't resolve my current problem, as it turns out.

**Comment by dlasky** [comment]
didnt see the edit in time sooo: https://github.com/dlasky/gotk3-layershell/commit/5cca0b8192612d5ed627efc41f497a49ca84333c

**Comment by dlasky** [comment]
what problem are you running into?

**Comment by nwg-piotr** [comment]
Nothing serious. I want my dock to be able to mimic various docks. When started as in Ubuntu, it overlaps the panel. If panel has been started after the dock, it looks all right:

![ubu](https://user-images.githubusercontent.com/20579136/113222982-78832400-9288-11eb-941a-718b5258a497.png)

If I start the dock after the panel, it behaves oddly:

![obraz](https://user-images.githubusercontent.com/20579136/113223034-93ee2f00-9288-11eb-8940-494958a08904.png)

Actually I'm not going to use the dock like this - if at all.

**Comment by nwg-piotr** [comment]
For daily use it looks better like this:

![obraz](https://user-images.githubusercontent.com/20579136/113223194-e596b980-9288-11eb-87a7-64b2822f716c.png)

**Comment by nwg-piotr** [comment]
And many thanks for adding what I asked for!

**Comment by dlasky** [comment]
No problem! Yeah unfortunately there are only a few layer choices otherwise I would say to bump the bar to a higher index but then it would likely overlap the Lock Screen as well.

**Comment by dlasky** [comment]
I wish I could run sway on my desktop as well. Stupid nvidia although I saw they are going to give up on egl streams thankfully

**Comment by dlasky** [comment]
Oh also there is the margin you can set from the anchor point

**Comment by nwg-piotr** [comment]
> Stupid nvidia

I remember back in May 2020 sway worked for me on nvidia, started with some stupid argument. Did they change this?

**Comment by dlasky** [comment]
it launches with --my-next-gpu-wont-be-nvidia but then running any other app and the CPU seems to spike to 800% (all cores maxed)

**Comment by nwg-piotr** [comment]
Shit. I bought my current all-AMD laptop with sway in mind, but it also would give me a big headache initially, until kernel 5.8.
