### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by t0fik** [dlasky/gotk3-layershell#7]
Please add explicit licensing statement.

**Comment by dlasky** [comment]
Feel free to research the dependencies and suggest one.

**Comment by t0fik** [comment]
`github.com/gotk3/gotk3` uses ISC license.
Other dependencies uses LGPL-2.0 or MPL-1.1.
I would opt for LGPL-3.0+.

**Comment by dlasky** [comment]
Sounds good. Will update this evening. Thank you!

**Comment by nwg-piotr** [comment]
I'm useless reading this legal gibberish. Does this imply any changes to my projects that use this library? They all use the MIT license.

**Comment by dlasky** [comment]
I hope not but if so we can change it

**Comment by nwg-piotr** [comment]
Hope so, too. I don't understand legal language even in Polish.

**Comment by t0fik** [comment]
In my understanding LGPL do not force GPL on projects, which use libraries licensed under it.
For me, more permissive license is also fine, eg: MIT or ISC
Lack of license at all is the problem

**Comment by dlasky** [comment]
Went with MIT just cause it seemed easier for @nwg-piotr but no strong opinions

**Comment by nwg-piotr** [comment]
Excellent, thank you very much!
